development:
  adapter: redis
  url: <% ENV.fetch("REDIS_URL") %>/1

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: rails_llm_production
